apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: runners.actions.summerwind.dev
spec:
  group: actions.summerwind.dev
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: runners
    singular: runner
    kind: Runner
    shortNames:
      - run