apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: k8s-file-runner
  namespace: actions
spec:
  replicas: 2
  template:
    spec:
      repository: nathanledall/k8s-files