name: Deploy to GKE and AKS test

on:
  push:
    branches:
      - main
permissions:
        id-token: write
        contents: read
        actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      path: docker_images/
      yaml: yaml_files/
      KUBE_CONFIG: ${{ secrets.AZ_KUBE_CONFIG_B64}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: create cube config
        run: |
            mkdir ${HOME}/.kube
            echo ${KUBE_CONFIG} | base64 --decode > ${HOME}/.kube/config 

      - name: test ls
        run: pwd
      
      - name: test connection to kubectl
        uses: actions-hub/kubectl@master
        with:
          args: |
            get pods
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          
      - name: Build and Push Docker Image
        run: |
            docker build -t php-app:latest -f ${path}"Dockerfile-php" .
            docker tag php-app:latest docker.io/nathanledall/php-app:latest
            docker push docker.io/nathanledall/php-app:latest

      - name: deploy to kubernetes
        uses: actions-hub/kubectl@master
        with:
          args: apply -f ${{env.yaml}}"deployment-php.yaml"
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.10.0
  
      - name: Build with Maven
        run: mvn clean install

      - name: Build and Push Docker Image
        run: |
            docker build -t spring-boot-app:latest -f ${path}"Dockerfile" .
            docker tag spring-boot-app:latest docker.io/nathanledall/spring-boot-app:latest
            docker push docker.io/nathanledall/spring-boot-app:latest
      
      - name: deploy to kubernetes
        uses: actions-hub/kubectl@master
        with:
          args: apply -f ${{env.yaml}}"deployment.yaml"