name: Deploy to GKE and AKS test

on:
  push:
    branches:
      - main
permissions:
        id-token: write
        contents: read
        actions: read
jobs:
  
  build-and-deploy:
    runs-on: self-hosted
    env:
      path: docker_images/
      yaml: yaml_files/
      KUBE_CONFIG: ${{ secrets.AZ_KUBE_CONFIG_B64}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: create cube config
        run: |
            mkdir ${HOME}/.kube
            echo ${KUBE_CONFIG} | base64 --decode > ${HOME}/.kube/config
      
      - name: test ls
        run: pwd
      
      - name: test connection to kubectl
        uses: actions-hub/kubectl@master
        with:
          args: get pods