name: Deploy to GKE and AKS test

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
        path: docker_images/
        yaml: yaml_files/

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
      
      #- name: ACR build
      #  id: build-push-acr
      #  uses: azure/acr-build@v1
      #  with:
      #    service_principal: ${{ secrets.service_principal }}
      #    service_principal_password: ${{ secrets.service_principal_password }}
      #    tenant: ${{ secrets.tenant }}
      #    registry: https://hub.docker.com/repository/docker/nathanledall/php-app/general
      #    repository: azuredocs
      #    image:  azure-vote-front
      #    folder: azure-vote
      #    branch: master
      #    tag: ${{ github.sha }}
      #    git_access_token: ${{secrets.git_access_token}}
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZ_JSON_LOGIN }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: group1 
          cluster-name: '${{ secrets.cluster_name }}'
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: 'default'
          manifests: |
             get pods
          images: https://hub.docker.com/repository/docker/nathanledall/php-app/general
          pull-images: false