name: Deploy to GKE and AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PROJECT_ID: inspired-verve-402211
      APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_JSON_KEY }}
      CLUSTER_NAME: gkekube
      ZONE_NAME: us-central1
      path: docker_images/
      yaml: yaml_files/
      tmp_token: a26b44e2a04df8b24c5d66805c4b60c0677feb16 #this token will be deleted very soon
      KUBE_CONFIG: ${{ secrets.GLCOU_KUBE_SETUP }}
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/123456789/locations/us-central1'
          service_account: 'github-actions@inspired-verve-402211.iam.gserviceaccount.com'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
  
      - name: 'Use gcloud CLI'
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GKE_SA_JSON_KEY }}
          gcloud info
          gcloud container clusters get-credentials gkekube
      
      - name: Get Pods
        run: |
          kubectl get pods
