name: Deploy to GKE and AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      #- id: 'auth'
      #  uses: 'google-github-actions/auth@v1'
      #  with:
      #    credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      #- name: 'Set up Cloud SDK'
      #  uses: 'google-github-actions/setup-gcloud@v1'

      #- name: 'Use gcloud CLI'
      #  run: 'kubectl get pods'

      - name: Set up Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.53.0
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            kubectl get pods
      
      #- name: Apply Kubernetes manifests to GKE
      #  run: kubectl get pods

      #- name: Disconnect from GKE
      #  run: gcloud auth revoke
      
      #- name: Login to Azure
      #  run: az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Apply Kubernetes manifests to AKS
        run: kubectl get pods