name: Deploy to GKE and AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PROJECT_ID: inspired-verve-402211
      APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_JSON_KEY }}
      CLUSTER_NAME: gkekube
      ZONE_NAME: us-central1-a
      path: docker_images/
      yaml: yaml_files/
      KUBE_CONFIG: ${{ secrets.GLCOU_KUBE_SETUP }}
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/inspired-verve-402211'
          service_account: '84569582463-compute@developer.gserviceaccount.com'
          project_id: inspired-verve-402211
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: gkekube
          location: us-central1-a
          project_id: inspired-verve-402211
      - name: test
        run: |
          gcloud config set account ACCOUNT
          kubectl get deployments
          kubectl get pods

      - name: 'Use gcloud CLI'
        run: 'kubectl get pods'

