name: Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    env:
      PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
      APPLICATION_CREDENTIALS: ${{ secrets.GKE_SA_JSON_KEY }}
      CLUSTER_NAME: gkekube
      ZONE_NAME: us-central1
      path: docker_images/
      yaml: yaml_files/
      tmp_token: ${{ secrets.TMP_TOKEN }} #this token will be deleted very soon
      KUBE_CONFIG: ${{ secrets.GLCOU_KUBE_SETUP }}
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/123456789/locations/us-central1'
          service_account: ${{ secrets.GKE_SA }}
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      - name: test name
        run: |
          gcloud components install kubectl
          echo "${{ secrets.GKE_SA_JSON_KEY }}" | base64 --decode > /tmp/key.json && gcloud auth activate-service-account --key-file=/tmp/key.json
      - name: 'Use gcloud CLI'
        run: |
          gcloud container clusters get-credentials gkekube --zone us-central1
          tanzu accelerator create -f accelerator.yaml

      
      #- name: Get Pods
      #  run: |
      #    kubectl get pods -n default
      #- name: Get Pods
      #  run: |
      #      kubectl apply -f test-github.yaml -n default
      #      kubectl get pods -n default
            


