name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
        path: docker_images/
        yaml: yaml_files/
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: create cube config
        run: |
            mkdir ${HOME}/.kube
            echo ${KUBE_CONFIG} | base64 --decode > ${HOME}/.kube/config
      
      - name: test ls
        run: pwd
      
      - name: test connection to kubectl
        uses: actions-hub/kubectl@master
        with:
          args: get pods -n actions
      #- name: Set Up Kubectl
      #  run: |
      #    kubectl config set-cluster local --server=localhost:8080
      #    kubectl config use-context local
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
      
      - name: Build and Push Docker Image
        run: |
            docker build -t php-app:latest -f ${path}"Dockerfile-php" .
            docker tag php-app:latest docker.io/nathanledall/php-app:latest
            docker push docker.io/nathanledall/php-app:latest
        
      #- name: Build Docker Image php-app
      #  run: docker build -t php-app:3.4.5 -f ${path}"Dockerfile-php" .


      #- name: load docker image to k8s php-app
      #  run: minikube image load php-app:3.0

      - name: deploy to kubernetes
        uses: actions-hub/kubectl@master
        with:
          args: apply -f ${{env.yaml}}"deployment-php.yaml"
      #- name: Deploy to Kubernetes
      #  run: kubectl apply -f $path"deployment-php.yaml"
