name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    

    env:
        path: docker_images/
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: create cube config
        run: |
            mkdir ${HOME}/.kube
            echo ${KUBE_CONFIG} | base64 --decode > ${HOME}/.kube/config
      
      - uses: actions-hub/kubectl@master
        with:
          args: get pods -n actions
      
      
      - name: Use context
        run: kubectl config use-context

      - name: Build Docker Image php-app
        run: docker build -t php-app:latest -f $path"Dockerfile-php" .

      - name: load docker image to k8s php-app
        run: minikube image load php-app:3.0

      - name: Deploy to Kubernetes
        run: kubectl apply -f $path"deployment-php.yaml"
